listenAddr = "127.0.0.1:5000"
verbose = true
#UserAgentID = "yourservernamehostname.example.org by yourcontactwebsite.org"

[gateway]
	# AllowedHosts = ["abc.localhost:8443", "abc.localhost:8080",	"myinternaldomain.local"] 
	[gateway.matrix]
		enabled = true
	[gateway.aesgcm] # used to convert the old deprecated webpush format
	    enabled = true
[rewrite]
	[rewrite.fcm]
		enabled = false
		# key = "" # key for any hostname
		[rewrite.fcm.Keys] # keys for specific hostnames
			#"your.fcm.hostname.example.org" = "YOUR_FCM_KEY"
			#"other.fcm.hostname.example.org" = "OTHER_FCM_KEY"
	[rewrite.gotify]
		enabled = false
		#address = "gotify1.unifiedpush.org:443"
		#scheme = "https"

# see https://github.com/UnifiedPush/common-proxies/blob/main/docs/config.md for more info
